### ISSUE TITLE
Bring up CP -> Pull container images fail

### ISSUE THREAD

**Issue by stefanronn** [KTH-EXPECA/kolla-ansible#5]
The procedure "Bring up the Control Plane" for chi in a box installation fails at
"pull container images", command "./cc-ansible --site /opt/site-config pull"
A cropped version of the log is attached. The complete log is available upon request.
[pull-fail-log-brief.txt](https://github.com/KTH-EXPECA/kolla-ansible/files/9937373/pull-fail-log-brief.txt)

**Comment by samiemostafavi** [comment]
It seems Ansible is not able to communicate with the docker registry. There is something wrong with your system's clock: `certificate has expired or is not yet valid: current time 2022-11-04T10:19:09Z is after 2022-11-03T22:01:59Z`

**Comment by stefanronn** [comment]
Are you referring to the VM's date/time? It seems accurate. The date 2022-11-03, where does that come from? Is that the expiry time of some certificate? In that case, it has expired...

**Comment by stefanronn** [comment]
It works now, so the problem must have been on the other side.
